### PR TITLE
fix: execution error when no file

### LINKED ISSUE #11: Stuck if app.ts is missing
If src folder is empty and no default app.ts when running `npm run sandbox` it will completely stuck

### PR DESCRIPTION
**Pull request by erhise**
Closes #11 even though the solution is a bit unclean. Refactoring tip appreciated.
There is no need to try/catch fs.exsistsSync after looking at source code => no error is ever thrown

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,8 +1,14 @@
 const { fileName } = require('./scripts/filename');
+const fs = require('fs');
 const nodemon = require('nodemon');
 
 const path = fileName(process.argv[2]);
 
+// ensure there are at least something to run
+if (path === 'src/app.ts' && fs.existsSync('src/app.ts') === false) {
```
Comment (siguse) [inline index.js:8]: Shouldn't we do the check regardless of the path?

Comment (siguse) [reply index.js:8]: Ah, nevermind. Now I see. We use app as a fallback :)

**Review by siguse — APPROVED** [review]
Wonderful 💯

**Comment by siguse** [comment]
> Closes #11 even though the solution is a bit unclean. Refactoring tip appreciated.
> There is no need to try/catch fs.exsistsSync after looking at source code => no error is ever thrown

I think it's a good solution. We could possibly think about how we can avoid the fs dependency in index. Maybe add another helper in filename.js?

**Comment by erhise** [comment]
> > Closes #11 even though the solution is a bit unclean. Refactoring tip appreciated.
> > There is no need to try/catch fs.exsistsSync after looking at source code => no error is ever thrown
> 
> I think it's a good solution. We could possibly think about how we can avoid the fs dependency in index. Maybe add another helper in filename.js?

Yeah, I wondered a little bit about the naming of the methods and how to use them; like the steps to follow is logical
1. Extract filename from input arguments
2. Check if file is valid
